service: rs-app-spa

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x


plugins:
  - serverless-finch
  - serverless-single-page-app-plugin

custom:
  client:
    bucketName: rss-app-spa-react
    distributionFolder: build

  s3BucketName: ${self:custom.client.bucketName}
  s3LocalPath: ${self:custom.client.distributionFolder}/

resources: ${file(./resources/cf-resources.yml)}